# ViT-CNN-crossview CPU Configuration
# Optimized for CPU training

model:
  name: "ViTCNN"
  backbone: "vit_small_patch16_224"
  num_classes: 10  # Reduced for faster training
  block_size: 3
  share_weights: true
  return_features: true
  dropout_rate: 0.1
  use_pretrained_resnet: false  # Disable for faster initialization
  use_pretrained_vit: false     # Disable for faster initialization
  num_final_clusters: 3
  resnet_layers: 18
  vit_patch_size: 16
  vit_embed_dim: 384  # Reduced from 768 for CPU efficiency

data:
  data_dir: "data/train"
  test_dir: "data/test"
  batch_size: 4      # Small batch size for CPU
  num_workers: 2     # Reduced for CPU
  image_height: 128  # Smaller images for CPU
  image_width: 128   # Smaller images for CPU
  views: 2
  sample_num: 4
  pad: 0
  color_jitter: false
  random_erasing_prob: 0.0

training:
  num_epochs: 5      # Reduced for testing
  learning_rate: 0.01
  weight_decay: 0.0005
  momentum: 0.9
  warm_epochs: 1     # Reduced warmup
  lr_scheduler_steps: [3]
  lr_scheduler_gamma: 0.1
  triplet_loss_weight: 0.3
  kl_loss_weight: 0.0
  use_kl_loss: false
  cross_attention_weight: 1.0
  use_fp16: false    # Disable mixed precision for CPU
  use_autocast: false # Disable autocast for CPU
  use_data_augmentation: false  # Disable for faster training
  moving_avg: 1.0
  optimizer: "sgd"
  scheduler: "step"

evaluation:
  eval_interval: 2   # Evaluate every 2 epochs
  save_plots: true
  plot_interval: 2
  metrics_to_track:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
  save_confusion_matrix: true
  save_roc_curves: false  # Disable for CPU efficiency
  save_training_curves: true

system:
  gpu_ids: ""        # No GPU
  use_gpu: false     # Force CPU usage
  seed: 42
  log_interval: 5    # More frequent logging
  save_interval: 5
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  pretrained_dir: "pretrained"
  log_level: "INFO"
  save_logs_to_file: true
  use_tensorboard: false
  use_wandb: false

mode: 0  # Training mode
