# ViT-CNN-crossview Configuration
# Compatible with PyTorch 2.1, CUDA 11.8, Ubuntu 18.04+

model:
  # Model type: "FSRA" or "ViTCNN"
  name: "ViTCNN"
  backbone: "vit_small_patch16_224"
  num_classes: 701
  block_size: 3
  share_weights: true
  return_features: true
  dropout_rate: 0.1

  # Pretrained model settings
  use_pretrained: true
  pretrained_path: "pretrained/vit_small_p16_224-15ec54c9.pth"

  # ViT-CNN specific settings
  use_pretrained_resnet: true
  use_pretrained_vit: false
  num_final_clusters: 3
  resnet_layers: 18  # ResNet18 backbone
  vit_patch_size: 16
  vit_embed_dim: 768

data:
  data_dir: "data/train"
  test_dir: "data/test"
  batch_size: 16
  num_workers: 4
  image_height: 256
  image_width: 256
  views: 2
  sample_num: 4
  pad: 0
  color_jitter: false
  random_erasing_prob: 0.0

training:
  num_epochs: 150
  learning_rate: 0.005
  weight_decay: 0.0005
  momentum: 0.9
  warm_epochs: 5
  lr_scheduler_steps: [70, 110]
  lr_scheduler_gamma: 0.1
  
  # Loss configuration
  triplet_loss_weight: 0.3
  kl_loss_weight: 0.0
  use_kl_loss: false
  cross_attention_weight: 1.0
  
  # Mixed precision training (enabled for PyTorch 2.1)
  use_fp16: false
  use_autocast: true
  
  # Data augmentation
  use_data_augmentation: true
  moving_avg: 1.0

evaluation:
  # Evaluation settings
  eval_interval: 10  # Evaluate every N epochs
  save_plots: true
  plot_interval: 10  # Save plots every N epochs
  metrics_to_track:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "auc_roc"
  
  # Visualization settings
  save_confusion_matrix: true
  save_roc_curves: true
  save_training_curves: true

system:
  gpu_ids: "0"
  use_gpu: true
  seed: 42
  log_interval: 10
  save_interval: 10
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  pretrained_dir: "pretrained"
  
  # Logging configuration
  log_level: "INFO"
  save_logs_to_file: true
  use_tensorboard: true
  use_wandb: false

# Mode: 0 for training, 1 for testing
mode: 0
