# FSRA_IMPROVED Configuration Optimized for Large Batch Sizes
# Your Innovation with Performance Optimizations

model:
  # Model type: "FSRA_IMPROVED" (your innovation)
  name: "FSRA_IMPROVED"
  num_classes: 701
  
  # Your innovation settings - optimized for large batches
  patch_size: 8                     # Reduced from 10 to 8 for efficiency
  num_final_clusters: 3             # Keep 3 communities
  feature_dim: 512                  # ResNet output dimension
  target_pca_dim: 128              # Reduced from 256 to 128 for efficiency
  share_weights: true
  
  # Community clustering settings (optimized)
  similarity_threshold: 0.6         # Higher threshold for fewer edges
  use_community_clustering: true    # Enable your innovation
  use_pca_alignment: true          # Enable PCA alignment
  
  # Pretrained model settings
  use_pretrained_resnet: true

data:
  data_dir: "data"
  test_dir: "data/test"
  batch_size: 64                   # Large batch size
  num_workers: 8                   # More workers for large batches
  image_height: 256
  image_width: 256
  views: 2
  sample_num: 4
  pad: 0
  color_jitter: true
  random_erasing_prob: 0.1

training:
  num_epochs: 50                   # Fewer epochs due to larger batches
  learning_rate: 0.008             # Higher LR for large batches (8x base)
  weight_decay: 0.0005
  momentum: 0.9
  warm_epochs: 3                   # Shorter warmup
  lr_scheduler_steps: [20, 35]     # Earlier decay
  lr_scheduler_gamma: 0.1
  
  # Loss weights
  triplet_loss_weight: 0.3
  kl_loss_weight: 0.0
  use_kl_loss: false
  alignment_loss_weight: 0.5
  
  # Training settings - optimized for large batches
  use_fp16: true                   # Enable mixed precision
  use_autocast: true               # Enable autocast
  use_data_augmentation: true
  moving_avg: 1.0
  optimizer: "sgd"
  scheduler: "step"

evaluation:
  eval_interval: 5                 # Less frequent evaluation
  save_plots: true
  plot_interval: 5
  metrics_to_track:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
  save_confusion_matrix: true
  save_roc_curves: false
  save_training_curves: true

system:
  gpu_ids: "0"
  use_gpu: true
  seed: 42
  log_interval: 5                  # Less frequent logging
  save_interval: 5
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  pretrained_dir: "pretrained"
  log_level: "INFO"
  save_logs_to_file: true
  use_tensorboard: false
  use_wandb: false

mode: 0  # Training mode
